import { intensityWindow } from './activityDirector';
import { DEFAULT_COLLABER, parseCollaber, type CollaberConfig } from './collaber/config';
export type PsychologyProfile={openness:'cautious'|'flexible'|'experimental';discipline:'spontaneous'|'organized'|'meticulous';extraversion:'reserved'|'social'|'outgoing';conflict:'avoidant'|'assertive'|'argumentative';emotionalReactivity:'calm'|'expressive'|'hot';impulsivity:'deliberate'|'balanced'|'immediate';directness:'diplomatic'|'direct'|'blunt';dominance:'non_dominant'|'confident'|'leading'};
export type ReactionProfile={criticism:'accepts'|'examines'|'sensitive';uncertainty:'cautious'|'investigates'|'risks';rudeness:'ignore'|'firm'|'humor';mistakes:'admits'|'verifies'|'defensive';selfDisclosure:'private'|'gradual'|'open';authority:'hierarchy'|'merit'|'skeptical'};
export type RelationshipStyle={bonding:'slow'|'normal'|'fast';trust:'guarded'|'balanced'|'trusting';repair:'remembers'|'gradual'|'quick';regulars:'distance'|'warmer'|'friends'};
export type PersonalityCore={goals:string[];strengths:string[];weaknesses:string[];boundaries:string[];triggers:string[];contradictions:string[]};
export type PersonalityProfile={psychology:PsychologyProfile;reactions:ReactionProfile;relationshipStyle:RelationshipStyle;core:PersonalityCore};
export const DEFAULT_PERSONALITY_PROFILE:PersonalityProfile={psychology:{openness:'flexible',discipline:'organized',extraversion:'social',conflict:'assertive',emotionalReactivity:'expressive',impulsivity:'balanced',directness:'direct',dominance:'confident'},reactions:{criticism:'examines',uncertainty:'investigates',rudeness:'humor',mistakes:'admits',selfDisclosure:'gradual',authority:'merit'},relationshipStyle:{bonding:'normal',trust:'balanced',repair:'gradual',regulars:'warmer'},core:{goals:[],strengths:[],weaknesses:[],boundaries:[],triggers:[],contradictions:[]}};
export type CommunityManagerConfigData = {
  features: { collaber: CollaberConfig };
  identity: { displayName: string; role: string; bio: string; preset: string; tone: 'friendly'|'expert'|'energetic'|'neutral'; addressForm: 'ты'|'вы'; socialRoles: string[]; traits: string[]; speechStyles: string[]; humorStyles: string[]; profanityLevel: 'none'|'mild'|'natural'|'rough'; debateStyle: 'avoid'|'gentle'|'fact_check'|'devils_advocate'|'provoke'|'defuse'; expertiseStances: string[]; collectiveAddress: string; verbalHabits: string[]; customInstructions: string; humorLevel: number; initiativeLevel: number; forbiddenClaims: string[] };
  support: { useBrandKit: boolean; useProjectDocs: boolean; useFaq: boolean; answerProductQuestions: boolean };
  personality: PersonalityProfile;
  research: { mode: 'off'|'when_needed'|'deep'; sourcePolicy: 'allowlist'|'open'; allowedDomains: string[]; blockedDomains: string[]; maxSearchesPerAnswer: number; dailyLimit: number };
  replies: { replyToDirectReply: boolean; replyToMention: boolean; replyToProductQuestion: boolean; replyToUnansweredQuestion: boolean; ambientConversation: boolean; thematicConversation: boolean; moderatorFollowups: boolean; conversationMemory: boolean; participationLevel: 'quiet'|'selective'|'active'; ambientCooldownMinutes: number; unansweredAfterMinutes: number; userCooldownSeconds: number };
  activities: { enabled: boolean; requireApproval: boolean; intensity:'quiet'|'balanced'|'active'; discussionEnabled: boolean; pollEnabled: boolean; quizEnabled:boolean; lightEnabled:boolean; hotNewsEnabled:boolean; digestEnabled: boolean; dailyDigestEnabled:boolean; dailyDigestHour:number; dailyDigestMinute:number; dailyDigestImageUrl:string; dailyDigestMaxTopics:number; predictionEnabled:boolean; challengeEnabled:boolean; contestEnabled:boolean; contentSupportEnabled:boolean; contentSilenceMinutes:number; rewardMode:'none'|'virtual'|'manual'; rewardDescription:string; responseWindowMinutes: number; topics: string[] };
  limits: { timezone: string; quietEnabled: boolean; quietFrom: number; quietTo: number; maxRepliesPerHour: number; maxRepliesPerDay: number };
};

export const DEFAULT_CM_CONFIG: CommunityManagerConfigData = {
  features: { collaber: DEFAULT_COLLABER },
  identity: { displayName: 'Community Manager', role: 'Комьюнити-менеджер проекта', bio: 'Помогаю участникам, поддерживаю полезные обсуждения и знаю продукт.', preset: 'friendly_guide', tone: 'friendly', addressForm: 'ты', socialRoles: ['Свой человек','Помощник новичков'], traits: ['Тёплый','Любопытный'], speechStyles: ['Разговорная','Простыми словами'], humorStyles: ['Лёгкий'], profanityLevel: 'none', debateStyle: 'gentle', expertiseStances: ['Собеседник на равных','Честно признаёт незнание'], collectiveAddress: 'Ребята', verbalHabits: ['Короткие сообщения'], customInstructions: '', humorLevel: 1, initiativeLevel: 1, forbiddenClaims: ['не обещать сроки, цены и действия команды без источника'] },
  support: { useBrandKit: true, useProjectDocs: true, useFaq: true, answerProductQuestions: true },
  personality:DEFAULT_PERSONALITY_PROFILE,
  research: { mode: 'when_needed', sourcePolicy: 'allowlist', allowedDomains: [], blockedDomains: ['youtube.com','youtu.be','tiktok.com','instagram.com','vk.com','dzen.ru'], maxSearchesPerAnswer: 3, dailyLimit: 20 },
  replies: { replyToDirectReply: true, replyToMention: true, replyToProductQuestion: true, replyToUnansweredQuestion: true, ambientConversation: true, thematicConversation: true, moderatorFollowups: true, conversationMemory: true, participationLevel: 'selective', ambientCooldownMinutes: 8, unansweredAfterMinutes: 15, userCooldownSeconds: 30 },
  activities: { enabled: true, requireApproval: false, intensity:'balanced', discussionEnabled: true, pollEnabled: true, quizEnabled:true, lightEnabled:true, hotNewsEnabled:true, digestEnabled: true, dailyDigestEnabled:false, dailyDigestHour:8, dailyDigestMinute:0, dailyDigestImageUrl:'', dailyDigestMaxTopics:4, predictionEnabled:true, challengeEnabled:false, contestEnabled:false, contentSupportEnabled:true, contentSilenceMinutes:20, rewardMode:'none', rewardDescription:'', responseWindowMinutes: 120, topics: [] },
  limits: { timezone: 'Europe/Moscow', quietEnabled: true, quietFrom: 23, quietTo: 9, maxRepliesPerHour: 20, maxRepliesPerDay: 100 },
};

const str=(v:unknown,f:string,max:number)=>typeof v==='string'&&v.trim()?v.trim().slice(0,max):f;
const num=(v:unknown,f:number,min:number,max:number)=>Math.max(min,Math.min(max,Number.isFinite(Number(v))?Number(v):f));
const bool=(v:unknown,f:boolean)=>typeof v==='boolean'?v:f;
const list=(v:unknown,maxItems:number,maxLen:number)=>Array.isArray(v)?[...new Set(v.filter(x=>typeof x==='string').map(x=>String(x).trim().slice(0,maxLen)).filter(Boolean))].slice(0,maxItems):[];
const listOr=(v:unknown,f:string[],maxItems:number,maxLen:number)=>Array.isArray(v)?list(v,maxItems,maxLen):f;
const domains=(v:unknown,maxItems=30)=>list(v,maxItems,200).map(x=>{try{return new URL(x.includes('://')?x:'https://'+x).hostname.toLowerCase().replace(/^www\\./,'')}catch{return''}}).filter(x=>/^[a-z0-9.-]+$/.test(x)&&x.includes('.')).filter((x,i,a)=>a.indexOf(x)===i);
const choice=<T extends string>(value:unknown,allowed:readonly T[],fallback:T):T=>allowed.includes(value as T)?value as T:fallback;
const safeImageUrl=(value:unknown)=>{if(typeof value!=='string')return'';const url=value.trim();return(url.startsWith('https://')||url.startsWith('http://')||url.startsWith('/uploads/'))?url.slice(0,1000):''};

export function parseCommunityManagerConfig(raw: unknown): CommunityManagerConfigData {
  const r=(raw&&typeof raw==='object'?raw:{}) as Record<string,any>, d=DEFAULT_CM_CONFIG;
  const identity=r.identity??{},support=r.support??{},research=r.research??{},replies=r.replies??{},activities=r.activities??{},limits=r.limits??{};
  const personality=r.personality??{},p=personality.psychology??{},re=personality.reactions??{},rs=personality.relationshipStyle??{},core=personality.core??{},pd=d.personality;
  const parsedPersonality:PersonalityProfile={psychology:{openness:choice(p.openness,['cautious','flexible','experimental'],pd.psychology.openness),discipline:choice(p.discipline,['spontaneous','organized','meticulous'],pd.psychology.discipline),extraversion:choice(p.extraversion,['reserved','social','outgoing'],pd.psychology.extraversion),conflict:choice(p.conflict,['avoidant','assertive','argumentative'],pd.psychology.conflict),emotionalReactivity:choice(p.emotionalReactivity,['calm','expressive','hot'],pd.psychology.emotionalReactivity),impulsivity:choice(p.impulsivity,['deliberate','balanced','immediate'],pd.psychology.impulsivity),directness:choice(p.directness,['diplomatic','direct','blunt'],pd.psychology.directness),dominance:choice(p.dominance,['non_dominant','confident','leading'],pd.psychology.dominance)},reactions:{criticism:choice(re.criticism,['accepts','examines','sensitive'],pd.reactions.criticism),uncertainty:choice(re.uncertainty,['cautious','investigates','risks'],pd.reactions.uncertainty),rudeness:choice(re.rudeness,['ignore','firm','humor'],pd.reactions.rudeness),mistakes:choice(re.mistakes,['admits','verifies','defensive'],pd.reactions.mistakes),selfDisclosure:choice(re.selfDisclosure,['private','gradual','open'],pd.reactions.selfDisclosure),authority:choice(re.authority,['hierarchy','merit','skeptical'],pd.reactions.authority)},relationshipStyle:{bonding:choice(rs.bonding,['slow','normal','fast'],pd.relationshipStyle.bonding),trust:choice(rs.trust,['guarded','balanced','trusting'],pd.relationshipStyle.trust),repair:choice(rs.repair,['remembers','gradual','quick'],pd.relationshipStyle.repair),regulars:choice(rs.regulars,['distance','warmer','friends'],pd.relationshipStyle.regulars)},core:{goals:list(core.goals,6,240),strengths:list(core.strengths,6,240),weaknesses:list(core.weaknesses,6,240),boundaries:list(core.boundaries,8,240),triggers:list(core.triggers,8,240),contradictions:list(core.contradictions,6,300)}};
  const tone=['friendly','expert','energetic','neutral'].includes(identity.tone)?identity.tone:d.identity.tone;
  const addressForm=['ты','вы'].includes(identity.addressForm)?identity.addressForm:d.identity.addressForm;
  const researchMode=['off','when_needed','deep'].includes(research.mode)?research.mode:d.research.mode;
  const sourcePolicy=['allowlist','open'].includes(research.sourcePolicy)?research.sourcePolicy:d.research.sourcePolicy;
  return {
    features:{collaber:parseCollaber(r.features?.collaber)},
    identity:{displayName:str(identity.displayName,d.identity.displayName,80),role:str(identity.role,d.identity.role,160),bio:str(identity.bio,d.identity.bio,2000),preset:str(identity.preset,d.identity.preset,80),tone,addressForm,socialRoles:listOr(identity.socialRoles,d.identity.socialRoles,4,80),traits:listOr(identity.traits,d.identity.traits,5,80),speechStyles:listOr(identity.speechStyles,d.identity.speechStyles,5,80),humorStyles:listOr(identity.humorStyles,d.identity.humorStyles,4,80),profanityLevel:['none','mild','natural','rough'].includes(identity.profanityLevel)?identity.profanityLevel:d.identity.profanityLevel,debateStyle:['avoid','gentle','fact_check','devils_advocate','provoke','defuse'].includes(identity.debateStyle)?identity.debateStyle:d.identity.debateStyle,expertiseStances:listOr(identity.expertiseStances,d.identity.expertiseStances,4,100),collectiveAddress:typeof identity.collectiveAddress==='string'?identity.collectiveAddress.trim().slice(0,80):d.identity.collectiveAddress,verbalHabits:listOr(identity.verbalHabits,d.identity.verbalHabits,6,100),customInstructions:typeof identity.customInstructions==='string'?identity.customInstructions.trim().slice(0,1200):'',humorLevel:num(identity.humorLevel,d.identity.humorLevel,0,3),initiativeLevel:num(identity.initiativeLevel,d.identity.initiativeLevel,0,3),forbiddenClaims:listOr(identity.forbiddenClaims,d.identity.forbiddenClaims,20,200)},
    support:{useBrandKit:bool(support.useBrandKit,d.support.useBrandKit),useProjectDocs:bool(support.useProjectDocs,d.support.useProjectDocs),useFaq:bool(support.useFaq,d.support.useFaq),answerProductQuestions:bool(support.answerProductQuestions,d.support.answerProductQuestions)},
    research:{mode:researchMode,sourcePolicy,allowedDomains:domains(research.allowedDomains),blockedDomains:domains(research.blockedDomains).length?domains(research.blockedDomains):d.research.blockedDomains,maxSearchesPerAnswer:num(research.maxSearchesPerAnswer,d.research.maxSearchesPerAnswer,1,5),dailyLimit:num(research.dailyLimit,d.research.dailyLimit,0,200)},
    personality:parsedPersonality,
    replies:{replyToDirectReply:bool(replies.replyToDirectReply,d.replies.replyToDirectReply),replyToMention:bool(replies.replyToMention,d.replies.replyToMention),replyToProductQuestion:bool(replies.replyToProductQuestion,d.replies.replyToProductQuestion),replyToUnansweredQuestion:bool(replies.replyToUnansweredQuestion,d.replies.replyToUnansweredQuestion),ambientConversation:bool(replies.ambientConversation,d.replies.ambientConversation),thematicConversation:bool(replies.thematicConversation,d.replies.thematicConversation),moderatorFollowups:bool(replies.moderatorFollowups,d.replies.moderatorFollowups),conversationMemory:bool(replies.conversationMemory,d.replies.conversationMemory),participationLevel:['quiet','selective','active'].includes(replies.participationLevel)?replies.participationLevel:d.replies.participationLevel,ambientCooldownMinutes:num(replies.ambientCooldownMinutes,d.replies.ambientCooldownMinutes,1,240),unansweredAfterMinutes:num(replies.unansweredAfterMinutes,d.replies.unansweredAfterMinutes,1,240),userCooldownSeconds:num(replies.userCooldownSeconds,d.replies.userCooldownSeconds,0,3600)},
    activities:{enabled:bool(activities.enabled,d.activities.enabled),requireApproval:bool(activities.requireApproval,d.activities.requireApproval),intensity:choice(activities.intensity,['quiet','balanced','active'],d.activities.intensity),discussionEnabled:bool(activities.discussionEnabled,d.activities.discussionEnabled),pollEnabled:bool(activities.pollEnabled,d.activities.pollEnabled),quizEnabled:bool(activities.quizEnabled,d.activities.quizEnabled),lightEnabled:bool(activities.lightEnabled,d.activities.lightEnabled),hotNewsEnabled:bool(activities.hotNewsEnabled,d.activities.hotNewsEnabled),digestEnabled:bool(activities.digestEnabled,d.activities.digestEnabled),dailyDigestEnabled:bool(activities.dailyDigestEnabled,d.activities.dailyDigestEnabled),dailyDigestHour:num(activities.dailyDigestHour,d.activities.dailyDigestHour,0,23),dailyDigestMinute:num(activities.dailyDigestMinute,d.activities.dailyDigestMinute,0,59),dailyDigestImageUrl:safeImageUrl(activities.dailyDigestImageUrl),dailyDigestMaxTopics:num(activities.dailyDigestMaxTopics,d.activities.dailyDigestMaxTopics,2,6),predictionEnabled:bool(activities.predictionEnabled,d.activities.predictionEnabled),challengeEnabled:bool(activities.challengeEnabled,d.activities.challengeEnabled),contestEnabled:bool(activities.contestEnabled,d.activities.contestEnabled),contentSupportEnabled:bool(activities.contentSupportEnabled,d.activities.contentSupportEnabled),contentSilenceMinutes:num(activities.contentSilenceMinutes,d.activities.contentSilenceMinutes,5,180),rewardMode:choice(activities.rewardMode,['none','virtual','manual'],d.activities.rewardMode),rewardDescription:typeof activities.rewardDescription==='string'?activities.rewardDescription.trim().slice(0,500):'',responseWindowMinutes:num(activities.responseWindowMinutes,d.activities.responseWindowMinutes,15,1440),topics:list(activities.topics,50,160)},
    limits:{timezone:str(limits.timezone,d.limits.timezone,80),quietEnabled:typeof limits.quietEnabled==='boolean'?limits.quietEnabled:num(limits.quietFrom,d.limits.quietFrom,0,23)!==num(limits.quietTo,d.limits.quietTo,0,23),quietFrom:num(limits.quietFrom,d.limits.quietFrom,0,23),quietTo:num(limits.quietTo,d.limits.quietTo,0,23),maxRepliesPerHour:num(limits.maxRepliesPerHour,d.limits.maxRepliesPerHour,1,100),maxRepliesPerDay:num(limits.maxRepliesPerDay,d.limits.maxRepliesPerDay,1,1000)},
  };
}

export function isQuietHour(config:CommunityManagerConfigData,date=new Date()):boolean{
  if(!config.limits.quietEnabled)return false;
  let hour=date.getUTCHours();
  try{hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:config.limits.timezone,hour:'2-digit',hourCycle:'h23'}).format(date));}catch{}
  const {quietFrom:a,quietTo:b}=config.limits;
  return a===b?false:a>b?(hour>=a||hour<b):(hour>=a&&hour<b);
}
export function randomInitiativeDate(config:CommunityManagerConfigData,from=new Date(),random=Math.random):Date{
  const {min,max}=intensityWindow(config.activities.intensity);
  const sample=Math.min(0.999999999,Math.max(0,random()));
  return new Date(from.getTime()+(min+Math.floor(sample*(max-min+1)))*60_000);
}
